kind: "Template"
apiVersion: "v1"
metadata:
  name: clarence-app
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: logstash
    spec:      
      tags:
      - name: latest
        from:
          kind: DockerImage
          name: docker.elastic.co/logstash/logstash:5.5.1
        importPolicy:
          scheduled: true
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      labels:
        app: logstash
      name: logstash
    spec:
      strategy:
        type: Recreate
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
            - logstash
            from:
              kind: ImageStreamTag
              name: logstash:latest
      replicas: 1
      template:
        metadata:
          labels:
            app: logstash
        spec:
          containers:
          - name: logstash
            image: logstash
